version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "dlq-test-ch"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1gywpu5ok5t95"
s3_prefix = "dlq-test-ch"
region = "ap-northeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
