version: '3'

services:
  dev-mysql:
    image: mysql:5.7
    container_name: dev-mysql
    ports:
      - "3308:3306"
    environment:
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /Users/Shared/data/dev-mysql-volume:/var/lib/mysql
    restart: always
    platform: 'linux/x86_64'


      